
function getForecastCurrentSmall() {
    return {
        "latitude": -23.9380377,
        "longitude": -46.286281,
        "timezone": "America/Sao_Paulo",
        "currently": {
            "time": 1521048080,
            "summary": "Úmido",
            "icon": "clear-day",
            "precipProbability": 0.10
        },
        "hourly": {
            "summary": "Úmido durante todo o dia e nublado começa durante a tarde de hoje.",
            "icon": "partly-cloudy-night",
            "data": [
                {
                    "time": 1521046800,
                    "summary": "Úmido",
                    "icon": "clear-day",
                    "precipIntensity": 0.3251,
                    "precipProbability": 0.12,
                    "precipType": "rain",
                    "temperature": 30.34,
                    "apparentTemperature": 37.37,
                    "dewPoint": 25.49,
                    "humidity": 0.75,
                    "pressure": 1010.61,
                    "windSpeed": 3.83,
                    "windGust": 5.17,
                    "windBearing": 162,
                    "cloudCover": 0.11,
                    "uvIndex": 9,
                    "visibility": 10.01,
                    "ozone": 251.18
                },
                {
                    "time": 1521050400,
                    "summary": "Úmido",
                    "icon": "clear-day",
                    "precipIntensity": 0.2565,
                    "precipProbability": 0.05,
                    "precipType": "rain",
                    "temperature": 29.4,
                    "apparentTemperature": 34.55,
                    "dewPoint": 24.34,
                    "humidity": 0.74,
                    "pressure": 1010.12,
                    "windSpeed": 3.15,
                    "windGust": 5.35,
                    "windBearing": 157,
                    "cloudCover": 0.22,
                    "uvIndex": 5,
                    "visibility": 10.01,
                    "ozone": 250.61
                },
                {
                    "time": 1521054000,
                    "summary": "Úmido e Ligeiramente Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.1524,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 28.67,
                    "apparentTemperature": 32.42,
                    "dewPoint": 23.19,
                    "humidity": 0.72,
                    "pressure": 1010.13,
                    "windSpeed": 2.59,
                    "windGust": 5.16,
                    "windBearing": 135,
                    "cloudCover": 0.42,
                    "uvIndex": 2,
                    "visibility": 10.01,
                    "ozone": 250.61
                },
                {
                    "time": 1521057600,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0406,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 28.19,
                    "apparentTemperature": 31.32,
                    "dewPoint": 22.63,
                    "humidity": 0.72,
                    "pressure": 1010.41,
                    "windSpeed": 2.45,
                    "windGust": 4.74,
                    "windBearing": 102,
                    "cloudCover": 0.67,
                    "uvIndex": 1,
                    "visibility": 10.01,
                    "ozone": 250.84
                },
                {
                    "time": 1521061200,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0051,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 28.01,
                    "apparentTemperature": 31.03,
                    "dewPoint": 22.62,
                    "humidity": 0.73,
                    "pressure": 1010.76,
                    "windSpeed": 2.46,
                    "windGust": 4.38,
                    "windBearing": 80,
                    "cloudCover": 0.86,
                    "uvIndex": 0,
                    "ozone": 250.87
                },
                {
                    "time": 1521064800,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 27.82,
                    "apparentTemperature": 30.74,
                    "dewPoint": 22.61,
                    "humidity": 0.73,
                    "pressure": 1011.26,
                    "windSpeed": 2.45,
                    "windGust": 4.18,
                    "windBearing": 72,
                    "cloudCover": 0.92,
                    "uvIndex": 0,
                    "ozone": 250.49
                },
                {
                    "time": 1521068400,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 27.62,
                    "apparentTemperature": 30.42,
                    "dewPoint": 22.58,
                    "humidity": 0.74,
                    "pressure": 1011.83,
                    "windSpeed": 2.33,
                    "windGust": 4.05,
                    "windBearing": 67,
                    "cloudCover": 0.93,
                    "uvIndex": 0,
                    "ozone": 249.82
                },
                {
                    "time": 1521072000,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 27.28,
                    "apparentTemperature": 29.88,
                    "dewPoint": 22.54,
                    "humidity": 0.75,
                    "pressure": 1012.19,
                    "windSpeed": 2.2,
                    "windGust": 3.92,
                    "windBearing": 61,
                    "cloudCover": 0.93,
                    "uvIndex": 0,
                    "ozone": 249.04
                },
                {
                    "time": 1521075600,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.0305,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 26.88,
                    "apparentTemperature": 29.23,
                    "dewPoint": 22.51,
                    "humidity": 0.77,
                    "pressure": 1012.15,
                    "windSpeed": 2.2,
                    "windGust": 3.68,
                    "windBearing": 56,
                    "cloudCover": 0.94,
                    "uvIndex": 0,
                    "ozone": 248.02
                },
                {
                    "time": 1521079200,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.1067,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 26.54,
                    "apparentTemperature": 28.64,
                    "dewPoint": 22.47,
                    "humidity": 0.78,
                    "pressure": 1011.91,
                    "windSpeed": 2.31,
                    "windGust": 3.48,
                    "windBearing": 49,
                    "cloudCover": 0.94,
                    "uvIndex": 0,
                    "ozone": 247.04
                },
                {
                    "time": 1521082800,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0.1575,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 26.28,
                    "apparentTemperature": 28.17,
                    "dewPoint": 22.37,
                    "humidity": 0.79,
                    "pressure": 1011.56,
                    "windSpeed": 2.39,
                    "windGust": 3.42,
                    "windBearing": 42,
                    "cloudCover": 0.93,
                    "uvIndex": 0,
                    "ozone": 246.11
                },
                {
                    "time": 1521086400,
                    "summary": "Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0.094,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 26.11,
                    "apparentTemperature": 27.84,
                    "dewPoint": 22.21,
                    "humidity": 0.79,
                    "pressure": 1011.06,
                    "windSpeed": 2.4,
                    "windGust": 3.68,
                    "windBearing": 31,
                    "cloudCover": 0.93,
                    "uvIndex": 0,
                    "ozone": 245.65
                },
                {
                    "time": 1521090000,
                    "summary": "Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0.0178,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 25.99,
                    "apparentTemperature": 27.61,
                    "dewPoint": 21.99,
                    "humidity": 0.79,
                    "pressure": 1010.47,
                    "windSpeed": 2.37,
                    "windGust": 4.09,
                    "windBearing": 17,
                    "cloudCover": 0.92,
                    "uvIndex": 0,
                    "ozone": 245.22
                },
                {
                    "time": 1521093600,
                    "summary": "Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 25.88,
                    "apparentTemperature": 26.57,
                    "dewPoint": 21.78,
                    "humidity": 0.78,
                    "pressure": 1010.05,
                    "windSpeed": 2.32,
                    "windGust": 4.26,
                    "windBearing": 6,
                    "cloudCover": 0.89,
                    "uvIndex": 0,
                    "ozone": 244.95
                },
                {
                    "time": 1521097200,
                    "summary": "Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 25.36,
                    "apparentTemperature": 26.03,
                    "dewPoint": 21.55,
                    "humidity": 0.8,
                    "pressure": 1009.84,
                    "windSpeed": 2.21,
                    "windGust": 3.93,
                    "windBearing": 352,
                    "cloudCover": 0.78,
                    "uvIndex": 0,
                    "ozone": 244.82
                },
                {
                    "time": 1521100800,
                    "summary": "Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 25.02,
                    "apparentTemperature": 25.67,
                    "dewPoint": 21.32,
                    "humidity": 0.8,
                    "pressure": 1009.78,
                    "windSpeed": 2.08,
                    "windGust": 3.37,
                    "windBearing": 340,
                    "cloudCover": 0.65,
                    "uvIndex": 0,
                    "ozone": 244.87
                },
                {
                    "time": 1521104400,
                    "summary": "Ligeiramente Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 25.32,
                    "apparentTemperature": 25.95,
                    "dewPoint": 21.29,
                    "humidity": 0.78,
                    "pressure": 1009.91,
                    "windSpeed": 2,
                    "windGust": 3.15,
                    "windBearing": 340,
                    "cloudCover": 0.56,
                    "uvIndex": 0,
                    "ozone": 245.15
                },
                {
                    "time": 1521108000,
                    "summary": "Ligeiramente Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 26.67,
                    "apparentTemperature": 28.58,
                    "dewPoint": 21.62,
                    "humidity": 0.74,
                    "pressure": 1010.36,
                    "windSpeed": 1.79,
                    "windGust": 3.61,
                    "windBearing": 6,
                    "cloudCover": 0.54,
                    "uvIndex": 0,
                    "ozone": 245.72
                },
                {
                    "time": 1521111600,
                    "summary": "Ligeiramente Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0178,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 28.6,
                    "apparentTemperature": 31.58,
                    "dewPoint": 22.14,
                    "humidity": 0.68,
                    "pressure": 1010.97,
                    "windSpeed": 1.69,
                    "windGust": 4.41,
                    "windBearing": 298,
                    "cloudCover": 0.57,
                    "uvIndex": 1,
                    "ozone": 246.42
                },
                {
                    "time": 1521115200,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0279,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 30.29,
                    "apparentTemperature": 34.16,
                    "dewPoint": 22.57,
                    "humidity": 0.63,
                    "pressure": 1011.32,
                    "windSpeed": 2.01,
                    "windGust": 5.03,
                    "windBearing": 315,
                    "cloudCover": 0.63,
                    "uvIndex": 3,
                    "ozone": 246.86
                },
                {
                    "time": 1521118800,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0178,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 31.77,
                    "apparentTemperature": 36.25,
                    "dewPoint": 22.74,
                    "humidity": 0.59,
                    "pressure": 1011.19,
                    "windSpeed": 1.84,
                    "windGust": 5.25,
                    "windBearing": 296,
                    "cloudCover": 0.75,
                    "uvIndex": 5,
                    "ozone": 246.7
                },
                {
                    "time": 1521122400,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 33.1,
                    "apparentTemperature": 38,
                    "dewPoint": 22.79,
                    "humidity": 0.55,
                    "pressure": 1010.83,
                    "windSpeed": 2.31,
                    "windGust": 5.28,
                    "windBearing": 329,
                    "cloudCover": 0.89,
                    "uvIndex": 7,
                    "ozone": 246.25
                },
                {
                    "time": 1521126000,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 34.33,
                    "apparentTemperature": 39.61,
                    "dewPoint": 22.82,
                    "humidity": 0.51,
                    "pressure": 1010.36,
                    "windSpeed": 2.51,
                    "windGust": 5.26,
                    "windBearing": 312,
                    "cloudCover": 1,
                    "uvIndex": 8,
                    "ozone": 245.96
                },
                {
                    "time": 1521129600,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.0025,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                    "temperature": 35.17,
                    "apparentTemperature": 40.77,
                    "dewPoint": 22.89,
                    "humidity": 0.49,
                    "pressure": 1009.77,
                    "windSpeed": 2.41,
                    "windGust": 5.31,
                    "windBearing": 327,
                    "cloudCover": 1,
                    "uvIndex": 7,
                    "ozone": 245.97
                },
                {
                    "time": 1521133200,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.0178,
                    "precipProbability": 0.06,
                    "precipType": "rain",
                    "temperature": 35.58,
                    "apparentTemperature": 41.35,
                    "dewPoint": 22.93,
                    "humidity": 0.48,
                    "pressure": 1009.09,
                    "windSpeed": 0.75,
                    "windGust": 5.3,
                    "windBearing": 312,
                    "cloudCover": 1,
                    "uvIndex": 5,
                    "ozone": 246.08
                },
                {
                    "time": 1521136800,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.0279,
                    "precipProbability": 0.06,
                    "precipType": "rain",
                    "temperature": 35.39,
                    "apparentTemperature": 41.17,
                    "dewPoint": 22.98,
                    "humidity": 0.49,
                    "pressure": 1008.69,
                    "windSpeed": 2.28,
                    "windGust": 5.06,
                    "windBearing": 286,
                    "cloudCover": 1,
                    "uvIndex": 3,
                    "ozone": 246.1
                },
                {
                    "time": 1521140400,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.0838,
                    "precipProbability": 0.06,
                    "precipType": "rain",
                    "temperature": 34.49,
                    "apparentTemperature": 40.11,
                    "dewPoint": 23.07,
                    "humidity": 0.52,
                    "pressure": 1008.68,
                    "windSpeed": 2.17,
                    "windGust": 4.4,
                    "windBearing": 278,
                    "cloudCover": 1,
                    "uvIndex": 1,
                    "ozone": 245.91
                },
                {
                    "time": 1521144000,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.381,
                    "precipProbability": 0.06,
                    "precipType": "rain",
                    "temperature": 33.15,
                    "apparentTemperature": 38.49,
                    "dewPoint": 23.18,
                    "humidity": 0.56,
                    "pressure": 1008.94,
                    "windSpeed": 0.44,
                    "windGust": 3.56,
                    "windBearing": 18,
                    "cloudCover": 1,
                    "uvIndex": 1,
                    "ozone": 245.53
                },
                {
                    "time": 1521147600,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.6883,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                    "temperature": 31.89,
                    "apparentTemperature": 36.83,
                    "dewPoint": 23.14,
                    "humidity": 0.6,
                    "pressure": 1009.37,
                    "windSpeed": 1.09,
                    "windGust": 3.01,
                    "windBearing": 24,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 245.38
                },
                {
                    "time": 1521151200,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.6452,
                    "precipProbability": 0.1,
                    "precipType": "rain",
                    "temperature": 30.94,
                    "apparentTemperature": 35.22,
                    "dewPoint": 22.78,
                    "humidity": 0.62,
                    "pressure": 1010.16,
                    "windSpeed": 0.85,
                    "windGust": 2.52,
                    "windBearing": 51,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 245.7
                },
                {
                    "time": 1521154800,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.5512,
                    "precipProbability": 0.13,
                    "precipType": "rain",
                    "temperature": 30.15,
                    "apparentTemperature": 33.74,
                    "dewPoint": 22.29,
                    "humidity": 0.63,
                    "pressure": 1011.14,
                    "windSpeed": 0.64,
                    "windGust": 2.07,
                    "windBearing": 102,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 246.38
                },
                {
                    "time": 1521158400,
                    "summary": "Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.4953,
                    "precipProbability": 0.13,
                    "precipType": "rain",
                    "temperature": 29.28,
                    "apparentTemperature": 32.38,
                    "dewPoint": 21.99,
                    "humidity": 0.65,
                    "pressure": 1011.82,
                    "windSpeed": 1.6,
                    "windGust": 1.87,
                    "windBearing": 347,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 246.84
                },
                {
                    "time": 1521162000,
                    "summary": "Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.2667,
                    "precipProbability": 0.11,
                    "precipType": "rain",
                    "temperature": 28.3,
                    "apparentTemperature": 31.11,
                    "dewPoint": 22.06,
                    "humidity": 0.69,
                    "pressure": 1011.97,
                    "windSpeed": 1.95,
                    "windGust": 2.17,
                    "windBearing": 334,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 246.84
                },
                {
                    "time": 1521165600,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.0483,
                    "precipProbability": 0.06,
                    "precipType": "rain",
                    "temperature": 27.36,
                    "apparentTemperature": 29.89,
                    "dewPoint": 22.32,
                    "humidity": 0.74,
                    "pressure": 1011.82,
                    "windSpeed": 1.9,
                    "windGust": 2.75,
                    "windBearing": 328,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 246.57
                },
                {
                    "time": 1521169200,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 26.66,
                    "apparentTemperature": 28.86,
                    "dewPoint": 22.5,
                    "humidity": 0.78,
                    "pressure": 1011.55,
                    "windSpeed": 2.45,
                    "windGust": 3.17,
                    "windBearing": 296,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 246.47
                },
                {
                    "time": 1521172800,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 26.27,
                    "apparentTemperature": 28.19,
                    "dewPoint": 22.49,
                    "humidity": 0.8,
                    "pressure": 1011.12,
                    "windSpeed": 2.14,
                    "windGust": 3.24,
                    "windBearing": 298,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 246.33
                },
                {
                    "time": 1521176400,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 26.16,
                    "apparentTemperature": 27.98,
                    "dewPoint": 22.43,
                    "humidity": 0.8,
                    "pressure": 1010.6,
                    "windSpeed": 1.52,
                    "windGust": 3.14,
                    "windBearing": 295,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 246.33
                },
                {
                    "time": 1521180000,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 26.02,
                    "apparentTemperature": 27.72,
                    "dewPoint": 22.39,
                    "humidity": 0.8,
                    "pressure": 1010.37,
                    "windSpeed": 1.6,
                    "windGust": 2.98,
                    "windBearing": 301,
                    "cloudCover": 0.99,
                    "uvIndex": 0,
                    "ozone": 246.45
                },
                {
                    "time": 1521183600,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.0356,
                    "precipProbability": 0.05,
                    "precipType": "rain",
                    "temperature": 25.77,
                    "apparentTemperature": 26.54,
                    "dewPoint": 22.41,
                    "humidity": 0.82,
                    "pressure": 1010.66,
                    "windSpeed": 1.89,
                    "windGust": 2.73,
                    "windBearing": 352,
                    "cloudCover": 0.97,
                    "uvIndex": 0,
                    "ozone": 246.63
                },
                {
                    "time": 1521187200,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0.1397,
                    "precipProbability": 0.08,
                    "precipType": "rain",
                    "temperature": 25.59,
                    "apparentTemperature": 26.38,
                    "dewPoint": 22.46,
                    "humidity": 0.83,
                    "pressure": 1011.26,
                    "windSpeed": 2.23,
                    "windGust": 2.49,
                    "windBearing": 200,
                    "cloudCover": 0.93,
                    "uvIndex": 0,
                    "ozone": 246.92
                },
                {
                    "time": 1521190800,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0.2261,
                    "precipProbability": 0.09,
                    "precipType": "rain",
                    "temperature": 25.66,
                    "apparentTemperature": 26.44,
                    "dewPoint": 22.55,
                    "humidity": 0.83,
                    "pressure": 1011.9,
                    "windSpeed": 2.51,
                    "windGust": 2.6,
                    "windBearing": 232,
                    "cloudCover": 0.91,
                    "uvIndex": 0,
                    "ozone": 247.16
                },
                {
                    "time": 1521194400,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.2032,
                    "precipProbability": 0.08,
                    "precipType": "rain",
                    "temperature": 26.1,
                    "apparentTemperature": 27.92,
                    "dewPoint": 22.67,
                    "humidity": 0.81,
                    "pressure": 1012.61,
                    "windSpeed": 1.86,
                    "windGust": 2.81,
                    "windBearing": 218,
                    "cloudCover": 0.91,
                    "uvIndex": 0,
                    "ozone": 247.16
                },
                {
                    "time": 1521198000,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.2692,
                    "precipProbability": 0.08,
                    "precipType": "rain",
                    "temperature": 26.82,
                    "apparentTemperature": 29.24,
                    "dewPoint": 22.81,
                    "humidity": 0.79,
                    "pressure": 1013.36,
                    "windSpeed": 2.51,
                    "windGust": 3.48,
                    "windBearing": 182,
                    "cloudCover": 0.93,
                    "uvIndex": 1,
                    "ozone": 247.18
                },
                {
                    "time": 1521201600,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.4293,
                    "precipProbability": 0.09,
                    "precipType": "rain",
                    "temperature": 27.43,
                    "apparentTemperature": 30.32,
                    "dewPoint": 22.91,
                    "humidity": 0.76,
                    "pressure": 1013.94,
                    "windSpeed": 2.66,
                    "windGust": 3.97,
                    "windBearing": 171,
                    "cloudCover": 0.94,
                    "uvIndex": 2,
                    "ozone": 246.92
                },
                {
                    "time": 1521205200,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.4877,
                    "precipProbability": 0.09,
                    "precipType": "rain",
                    "temperature": 28.02,
                    "apparentTemperature": 31.29,
                    "dewPoint": 22.99,
                    "humidity": 0.74,
                    "pressure": 1014.25,
                    "windSpeed": 2.66,
                    "windGust": 4.02,
                    "windBearing": 174,
                    "cloudCover": 0.9,
                    "uvIndex": 4,
                    "ozone": 246.49
                },
                {
                    "time": 1521208800,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.4801,
                    "precipProbability": 0.08,
                    "precipType": "rain",
                    "temperature": 28.54,
                    "apparentTemperature": 32.11,
                    "dewPoint": 23.04,
                    "humidity": 0.72,
                    "pressure": 1014.37,
                    "windSpeed": 2.67,
                    "windGust": 3.88,
                    "windBearing": 179,
                    "cloudCover": 0.85,
                    "uvIndex": 7,
                    "ozone": 246.01
                },
                {
                    "time": 1521212400,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.447,
                    "precipProbability": 0.07,
                    "precipType": "rain",
                    "temperature": 29.06,
                    "apparentTemperature": 32.91,
                    "dewPoint": 23.09,
                    "humidity": 0.7,
                    "pressure": 1014.24,
                    "windSpeed": 2.66,
                    "windGust": 3.8,
                    "windBearing": 182,
                    "cloudCover": 0.82,
                    "uvIndex": 9,
                    "ozone": 245.55
                },
                {
                    "time": 1521216000,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.3632,
                    "precipProbability": 0.07,
                    "precipType": "rain",
                    "temperature": 29.39,
                    "apparentTemperature": 33.44,
                    "dewPoint": 23.13,
                    "humidity": 0.69,
                    "pressure": 1013.65,
                    "windSpeed": 2.75,
                    "windGust": 3.89,
                    "windBearing": 178,
                    "cloudCover": 0.83,
                    "uvIndex": 8,
                    "ozone": 245
                },
                {
                    "time": 1521219600,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.254,
                    "precipProbability": 0.07,
                    "precipType": "rain",
                    "temperature": 29.54,
                    "apparentTemperature": 33.66,
                    "dewPoint": 23.16,
                    "humidity": 0.69,
                    "pressure": 1012.82,
                    "windSpeed": 2.87,
                    "windGust": 4.03,
                    "windBearing": 172,
                    "cloudCover": 0.86,
                    "uvIndex": 6,
                    "ozone": 244.59
                }
            ]
        },
        "offset": -3
    }
}


function getForecastCurrentGreat() {
    return {
        "latitude": -23.9380377,
        "longitude": -46.286281,
        "timezone": "America/Sao_Paulo",
        "currently": {
            "time": 1521048080,
            "summary": "Úmido",
            "icon": "clear-day",
            "precipProbability": 0.83
        },
        "hourly": {
            "summary": "Úmido durante todo o dia e nublado começa durante a tarde de hoje.",
            "icon": "partly-cloudy-night",
            "data": [
                {
                    "time": 1521046800,
                    "summary": "Úmido",
                    "icon": "clear-day",
                    "precipIntensity": 0.3251,
                    "precipProbability": 0.12,
                    "precipType": "rain",
                    "temperature": 30.34,
                    "apparentTemperature": 37.37,
                    "dewPoint": 25.49,
                    "humidity": 0.75,
                    "pressure": 1010.61,
                    "windSpeed": 3.83,
                    "windGust": 5.17,
                    "windBearing": 162,
                    "cloudCover": 0.11,
                    "uvIndex": 9,
                    "visibility": 10.01,
                    "ozone": 251.18
                },
                {
                    "time": 1521050400,
                    "summary": "Úmido",
                    "icon": "clear-day",
                    "precipIntensity": 0.2565,
                    "precipProbability": 0.05,
                    "precipType": "rain",
                    "temperature": 29.4,
                    "apparentTemperature": 34.55,
                    "dewPoint": 24.34,
                    "humidity": 0.74,
                    "pressure": 1010.12,
                    "windSpeed": 3.15,
                    "windGust": 5.35,
                    "windBearing": 157,
                    "cloudCover": 0.22,
                    "uvIndex": 5,
                    "visibility": 10.01,
                    "ozone": 250.61
                },
                {
                    "time": 1521054000,
                    "summary": "Úmido e Ligeiramente Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.1524,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 28.67,
                    "apparentTemperature": 32.42,
                    "dewPoint": 23.19,
                    "humidity": 0.72,
                    "pressure": 1010.13,
                    "windSpeed": 2.59,
                    "windGust": 5.16,
                    "windBearing": 135,
                    "cloudCover": 0.42,
                    "uvIndex": 2,
                    "visibility": 10.01,
                    "ozone": 250.61
                },
                {
                    "time": 1521057600,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0406,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 28.19,
                    "apparentTemperature": 31.32,
                    "dewPoint": 22.63,
                    "humidity": 0.72,
                    "pressure": 1010.41,
                    "windSpeed": 2.45,
                    "windGust": 4.74,
                    "windBearing": 102,
                    "cloudCover": 0.67,
                    "uvIndex": 1,
                    "visibility": 10.01,
                    "ozone": 250.84
                },
                {
                    "time": 1521061200,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0051,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 28.01,
                    "apparentTemperature": 31.03,
                    "dewPoint": 22.62,
                    "humidity": 0.73,
                    "pressure": 1010.76,
                    "windSpeed": 2.46,
                    "windGust": 4.38,
                    "windBearing": 80,
                    "cloudCover": 0.86,
                    "uvIndex": 0,
                    "ozone": 250.87
                },
                {
                    "time": 1521064800,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 27.82,
                    "apparentTemperature": 30.74,
                    "dewPoint": 22.61,
                    "humidity": 0.73,
                    "pressure": 1011.26,
                    "windSpeed": 2.45,
                    "windGust": 4.18,
                    "windBearing": 72,
                    "cloudCover": 0.92,
                    "uvIndex": 0,
                    "ozone": 250.49
                },
                {
                    "time": 1521068400,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 27.62,
                    "apparentTemperature": 30.42,
                    "dewPoint": 22.58,
                    "humidity": 0.74,
                    "pressure": 1011.83,
                    "windSpeed": 2.33,
                    "windGust": 4.05,
                    "windBearing": 67,
                    "cloudCover": 0.93,
                    "uvIndex": 0,
                    "ozone": 249.82
                },
                {
                    "time": 1521072000,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 27.28,
                    "apparentTemperature": 29.88,
                    "dewPoint": 22.54,
                    "humidity": 0.75,
                    "pressure": 1012.19,
                    "windSpeed": 2.2,
                    "windGust": 3.92,
                    "windBearing": 61,
                    "cloudCover": 0.93,
                    "uvIndex": 0,
                    "ozone": 249.04
                },
                {
                    "time": 1521075600,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.0305,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 26.88,
                    "apparentTemperature": 29.23,
                    "dewPoint": 22.51,
                    "humidity": 0.77,
                    "pressure": 1012.15,
                    "windSpeed": 2.2,
                    "windGust": 3.68,
                    "windBearing": 56,
                    "cloudCover": 0.94,
                    "uvIndex": 0,
                    "ozone": 248.02
                },
                {
                    "time": 1521079200,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.1067,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 26.54,
                    "apparentTemperature": 28.64,
                    "dewPoint": 22.47,
                    "humidity": 0.78,
                    "pressure": 1011.91,
                    "windSpeed": 2.31,
                    "windGust": 3.48,
                    "windBearing": 49,
                    "cloudCover": 0.94,
                    "uvIndex": 0,
                    "ozone": 247.04
                },
                {
                    "time": 1521082800,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0.1575,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 26.28,
                    "apparentTemperature": 28.17,
                    "dewPoint": 22.37,
                    "humidity": 0.79,
                    "pressure": 1011.56,
                    "windSpeed": 2.39,
                    "windGust": 3.42,
                    "windBearing": 42,
                    "cloudCover": 0.93,
                    "uvIndex": 0,
                    "ozone": 246.11
                },
                {
                    "time": 1521086400,
                    "summary": "Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0.094,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 26.11,
                    "apparentTemperature": 27.84,
                    "dewPoint": 22.21,
                    "humidity": 0.79,
                    "pressure": 1011.06,
                    "windSpeed": 2.4,
                    "windGust": 3.68,
                    "windBearing": 31,
                    "cloudCover": 0.93,
                    "uvIndex": 0,
                    "ozone": 245.65
                },
                {
                    "time": 1521090000,
                    "summary": "Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0.0178,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 25.99,
                    "apparentTemperature": 27.61,
                    "dewPoint": 21.99,
                    "humidity": 0.79,
                    "pressure": 1010.47,
                    "windSpeed": 2.37,
                    "windGust": 4.09,
                    "windBearing": 17,
                    "cloudCover": 0.92,
                    "uvIndex": 0,
                    "ozone": 245.22
                },
                {
                    "time": 1521093600,
                    "summary": "Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 25.88,
                    "apparentTemperature": 26.57,
                    "dewPoint": 21.78,
                    "humidity": 0.78,
                    "pressure": 1010.05,
                    "windSpeed": 2.32,
                    "windGust": 4.26,
                    "windBearing": 6,
                    "cloudCover": 0.89,
                    "uvIndex": 0,
                    "ozone": 244.95
                },
                {
                    "time": 1521097200,
                    "summary": "Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 25.36,
                    "apparentTemperature": 26.03,
                    "dewPoint": 21.55,
                    "humidity": 0.8,
                    "pressure": 1009.84,
                    "windSpeed": 2.21,
                    "windGust": 3.93,
                    "windBearing": 352,
                    "cloudCover": 0.78,
                    "uvIndex": 0,
                    "ozone": 244.82
                },
                {
                    "time": 1521100800,
                    "summary": "Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 25.02,
                    "apparentTemperature": 25.67,
                    "dewPoint": 21.32,
                    "humidity": 0.8,
                    "pressure": 1009.78,
                    "windSpeed": 2.08,
                    "windGust": 3.37,
                    "windBearing": 340,
                    "cloudCover": 0.65,
                    "uvIndex": 0,
                    "ozone": 244.87
                },
                {
                    "time": 1521104400,
                    "summary": "Ligeiramente Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 25.32,
                    "apparentTemperature": 25.95,
                    "dewPoint": 21.29,
                    "humidity": 0.78,
                    "pressure": 1009.91,
                    "windSpeed": 2,
                    "windGust": 3.15,
                    "windBearing": 340,
                    "cloudCover": 0.56,
                    "uvIndex": 0,
                    "ozone": 245.15
                },
                {
                    "time": 1521108000,
                    "summary": "Ligeiramente Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 26.67,
                    "apparentTemperature": 28.58,
                    "dewPoint": 21.62,
                    "humidity": 0.74,
                    "pressure": 1010.36,
                    "windSpeed": 1.79,
                    "windGust": 3.61,
                    "windBearing": 6,
                    "cloudCover": 0.54,
                    "uvIndex": 0,
                    "ozone": 245.72
                },
                {
                    "time": 1521111600,
                    "summary": "Ligeiramente Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0178,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 28.6,
                    "apparentTemperature": 31.58,
                    "dewPoint": 22.14,
                    "humidity": 0.68,
                    "pressure": 1010.97,
                    "windSpeed": 1.69,
                    "windGust": 4.41,
                    "windBearing": 298,
                    "cloudCover": 0.57,
                    "uvIndex": 1,
                    "ozone": 246.42
                },
                {
                    "time": 1521115200,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0279,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 30.29,
                    "apparentTemperature": 34.16,
                    "dewPoint": 22.57,
                    "humidity": 0.63,
                    "pressure": 1011.32,
                    "windSpeed": 2.01,
                    "windGust": 5.03,
                    "windBearing": 315,
                    "cloudCover": 0.63,
                    "uvIndex": 3,
                    "ozone": 246.86
                },
                {
                    "time": 1521118800,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0178,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 31.77,
                    "apparentTemperature": 36.25,
                    "dewPoint": 22.74,
                    "humidity": 0.59,
                    "pressure": 1011.19,
                    "windSpeed": 1.84,
                    "windGust": 5.25,
                    "windBearing": 296,
                    "cloudCover": 0.75,
                    "uvIndex": 5,
                    "ozone": 246.7
                },
                {
                    "time": 1521122400,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 33.1,
                    "apparentTemperature": 38,
                    "dewPoint": 22.79,
                    "humidity": 0.55,
                    "pressure": 1010.83,
                    "windSpeed": 2.31,
                    "windGust": 5.28,
                    "windBearing": 329,
                    "cloudCover": 0.89,
                    "uvIndex": 7,
                    "ozone": 246.25
                },
                {
                    "time": 1521126000,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 34.33,
                    "apparentTemperature": 39.61,
                    "dewPoint": 22.82,
                    "humidity": 0.51,
                    "pressure": 1010.36,
                    "windSpeed": 2.51,
                    "windGust": 5.26,
                    "windBearing": 312,
                    "cloudCover": 1,
                    "uvIndex": 8,
                    "ozone": 245.96
                },
                {
                    "time": 1521129600,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.0025,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                    "temperature": 35.17,
                    "apparentTemperature": 40.77,
                    "dewPoint": 22.89,
                    "humidity": 0.49,
                    "pressure": 1009.77,
                    "windSpeed": 2.41,
                    "windGust": 5.31,
                    "windBearing": 327,
                    "cloudCover": 1,
                    "uvIndex": 7,
                    "ozone": 245.97
                },
                {
                    "time": 1521133200,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.0178,
                    "precipProbability": 0.06,
                    "precipType": "rain",
                    "temperature": 35.58,
                    "apparentTemperature": 41.35,
                    "dewPoint": 22.93,
                    "humidity": 0.48,
                    "pressure": 1009.09,
                    "windSpeed": 0.75,
                    "windGust": 5.3,
                    "windBearing": 312,
                    "cloudCover": 1,
                    "uvIndex": 5,
                    "ozone": 246.08
                },
                {
                    "time": 1521136800,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.0279,
                    "precipProbability": 0.06,
                    "precipType": "rain",
                    "temperature": 35.39,
                    "apparentTemperature": 41.17,
                    "dewPoint": 22.98,
                    "humidity": 0.49,
                    "pressure": 1008.69,
                    "windSpeed": 2.28,
                    "windGust": 5.06,
                    "windBearing": 286,
                    "cloudCover": 1,
                    "uvIndex": 3,
                    "ozone": 246.1
                },
                {
                    "time": 1521140400,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.0838,
                    "precipProbability": 0.06,
                    "precipType": "rain",
                    "temperature": 34.49,
                    "apparentTemperature": 40.11,
                    "dewPoint": 23.07,
                    "humidity": 0.52,
                    "pressure": 1008.68,
                    "windSpeed": 2.17,
                    "windGust": 4.4,
                    "windBearing": 278,
                    "cloudCover": 1,
                    "uvIndex": 1,
                    "ozone": 245.91
                },
                {
                    "time": 1521144000,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.381,
                    "precipProbability": 0.06,
                    "precipType": "rain",
                    "temperature": 33.15,
                    "apparentTemperature": 38.49,
                    "dewPoint": 23.18,
                    "humidity": 0.56,
                    "pressure": 1008.94,
                    "windSpeed": 0.44,
                    "windGust": 3.56,
                    "windBearing": 18,
                    "cloudCover": 1,
                    "uvIndex": 1,
                    "ozone": 245.53
                },
                {
                    "time": 1521147600,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.6883,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                    "temperature": 31.89,
                    "apparentTemperature": 36.83,
                    "dewPoint": 23.14,
                    "humidity": 0.6,
                    "pressure": 1009.37,
                    "windSpeed": 1.09,
                    "windGust": 3.01,
                    "windBearing": 24,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 245.38
                },
                {
                    "time": 1521151200,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.6452,
                    "precipProbability": 0.1,
                    "precipType": "rain",
                    "temperature": 30.94,
                    "apparentTemperature": 35.22,
                    "dewPoint": 22.78,
                    "humidity": 0.62,
                    "pressure": 1010.16,
                    "windSpeed": 0.85,
                    "windGust": 2.52,
                    "windBearing": 51,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 245.7
                },
                {
                    "time": 1521154800,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.5512,
                    "precipProbability": 0.13,
                    "precipType": "rain",
                    "temperature": 30.15,
                    "apparentTemperature": 33.74,
                    "dewPoint": 22.29,
                    "humidity": 0.63,
                    "pressure": 1011.14,
                    "windSpeed": 0.64,
                    "windGust": 2.07,
                    "windBearing": 102,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 246.38
                },
                {
                    "time": 1521158400,
                    "summary": "Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.4953,
                    "precipProbability": 0.13,
                    "precipType": "rain",
                    "temperature": 29.28,
                    "apparentTemperature": 32.38,
                    "dewPoint": 21.99,
                    "humidity": 0.65,
                    "pressure": 1011.82,
                    "windSpeed": 1.6,
                    "windGust": 1.87,
                    "windBearing": 347,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 246.84
                },
                {
                    "time": 1521162000,
                    "summary": "Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.2667,
                    "precipProbability": 0.11,
                    "precipType": "rain",
                    "temperature": 28.3,
                    "apparentTemperature": 31.11,
                    "dewPoint": 22.06,
                    "humidity": 0.69,
                    "pressure": 1011.97,
                    "windSpeed": 1.95,
                    "windGust": 2.17,
                    "windBearing": 334,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 246.84
                },
                {
                    "time": 1521165600,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.0483,
                    "precipProbability": 0.06,
                    "precipType": "rain",
                    "temperature": 27.36,
                    "apparentTemperature": 29.89,
                    "dewPoint": 22.32,
                    "humidity": 0.74,
                    "pressure": 1011.82,
                    "windSpeed": 1.9,
                    "windGust": 2.75,
                    "windBearing": 328,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 246.57
                },
                {
                    "time": 1521169200,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 26.66,
                    "apparentTemperature": 28.86,
                    "dewPoint": 22.5,
                    "humidity": 0.78,
                    "pressure": 1011.55,
                    "windSpeed": 2.45,
                    "windGust": 3.17,
                    "windBearing": 296,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 246.47
                },
                {
                    "time": 1521172800,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 26.27,
                    "apparentTemperature": 28.19,
                    "dewPoint": 22.49,
                    "humidity": 0.8,
                    "pressure": 1011.12,
                    "windSpeed": 2.14,
                    "windGust": 3.24,
                    "windBearing": 298,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 246.33
                },
                {
                    "time": 1521176400,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 26.16,
                    "apparentTemperature": 27.98,
                    "dewPoint": 22.43,
                    "humidity": 0.8,
                    "pressure": 1010.6,
                    "windSpeed": 1.52,
                    "windGust": 3.14,
                    "windBearing": 295,
                    "cloudCover": 1,
                    "uvIndex": 0,
                    "ozone": 246.33
                },
                {
                    "time": 1521180000,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 26.02,
                    "apparentTemperature": 27.72,
                    "dewPoint": 22.39,
                    "humidity": 0.8,
                    "pressure": 1010.37,
                    "windSpeed": 1.6,
                    "windGust": 2.98,
                    "windBearing": 301,
                    "cloudCover": 0.99,
                    "uvIndex": 0,
                    "ozone": 246.45
                },
                {
                    "time": 1521183600,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.0356,
                    "precipProbability": 0.05,
                    "precipType": "rain",
                    "temperature": 25.77,
                    "apparentTemperature": 26.54,
                    "dewPoint": 22.41,
                    "humidity": 0.82,
                    "pressure": 1010.66,
                    "windSpeed": 1.89,
                    "windGust": 2.73,
                    "windBearing": 352,
                    "cloudCover": 0.97,
                    "uvIndex": 0,
                    "ozone": 246.63
                },
                {
                    "time": 1521187200,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0.1397,
                    "precipProbability": 0.08,
                    "precipType": "rain",
                    "temperature": 25.59,
                    "apparentTemperature": 26.38,
                    "dewPoint": 22.46,
                    "humidity": 0.83,
                    "pressure": 1011.26,
                    "windSpeed": 2.23,
                    "windGust": 2.49,
                    "windBearing": 200,
                    "cloudCover": 0.93,
                    "uvIndex": 0,
                    "ozone": 246.92
                },
                {
                    "time": 1521190800,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0.2261,
                    "precipProbability": 0.09,
                    "precipType": "rain",
                    "temperature": 25.66,
                    "apparentTemperature": 26.44,
                    "dewPoint": 22.55,
                    "humidity": 0.83,
                    "pressure": 1011.9,
                    "windSpeed": 2.51,
                    "windGust": 2.6,
                    "windBearing": 232,
                    "cloudCover": 0.91,
                    "uvIndex": 0,
                    "ozone": 247.16
                },
                {
                    "time": 1521194400,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.2032,
                    "precipProbability": 0.08,
                    "precipType": "rain",
                    "temperature": 26.1,
                    "apparentTemperature": 27.92,
                    "dewPoint": 22.67,
                    "humidity": 0.81,
                    "pressure": 1012.61,
                    "windSpeed": 1.86,
                    "windGust": 2.81,
                    "windBearing": 218,
                    "cloudCover": 0.91,
                    "uvIndex": 0,
                    "ozone": 247.16
                },
                {
                    "time": 1521198000,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.2692,
                    "precipProbability": 0.08,
                    "precipType": "rain",
                    "temperature": 26.82,
                    "apparentTemperature": 29.24,
                    "dewPoint": 22.81,
                    "humidity": 0.79,
                    "pressure": 1013.36,
                    "windSpeed": 2.51,
                    "windGust": 3.48,
                    "windBearing": 182,
                    "cloudCover": 0.93,
                    "uvIndex": 1,
                    "ozone": 247.18
                },
                {
                    "time": 1521201600,
                    "summary": "Úmido e Muito Nublado",
                    "icon": "cloudy",
                    "precipIntensity": 0.4293,
                    "precipProbability": 0.09,
                    "precipType": "rain",
                    "temperature": 27.43,
                    "apparentTemperature": 30.32,
                    "dewPoint": 22.91,
                    "humidity": 0.76,
                    "pressure": 1013.94,
                    "windSpeed": 2.66,
                    "windGust": 3.97,
                    "windBearing": 171,
                    "cloudCover": 0.94,
                    "uvIndex": 2,
                    "ozone": 246.92
                },
                {
                    "time": 1521205200,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.4877,
                    "precipProbability": 0.09,
                    "precipType": "rain",
                    "temperature": 28.02,
                    "apparentTemperature": 31.29,
                    "dewPoint": 22.99,
                    "humidity": 0.74,
                    "pressure": 1014.25,
                    "windSpeed": 2.66,
                    "windGust": 4.02,
                    "windBearing": 174,
                    "cloudCover": 0.9,
                    "uvIndex": 4,
                    "ozone": 246.49
                },
                {
                    "time": 1521208800,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.4801,
                    "precipProbability": 0.08,
                    "precipType": "rain",
                    "temperature": 28.54,
                    "apparentTemperature": 32.11,
                    "dewPoint": 23.04,
                    "humidity": 0.72,
                    "pressure": 1014.37,
                    "windSpeed": 2.67,
                    "windGust": 3.88,
                    "windBearing": 179,
                    "cloudCover": 0.85,
                    "uvIndex": 7,
                    "ozone": 246.01
                },
                {
                    "time": 1521212400,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.447,
                    "precipProbability": 0.07,
                    "precipType": "rain",
                    "temperature": 29.06,
                    "apparentTemperature": 32.91,
                    "dewPoint": 23.09,
                    "humidity": 0.7,
                    "pressure": 1014.24,
                    "windSpeed": 2.66,
                    "windGust": 3.8,
                    "windBearing": 182,
                    "cloudCover": 0.82,
                    "uvIndex": 9,
                    "ozone": 245.55
                },
                {
                    "time": 1521216000,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.3632,
                    "precipProbability": 0.07,
                    "precipType": "rain",
                    "temperature": 29.39,
                    "apparentTemperature": 33.44,
                    "dewPoint": 23.13,
                    "humidity": 0.69,
                    "pressure": 1013.65,
                    "windSpeed": 2.75,
                    "windGust": 3.89,
                    "windBearing": 178,
                    "cloudCover": 0.83,
                    "uvIndex": 8,
                    "ozone": 245
                },
                {
                    "time": 1521219600,
                    "summary": "Úmido e Nublado",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.254,
                    "precipProbability": 0.07,
                    "precipType": "rain",
                    "temperature": 29.54,
                    "apparentTemperature": 33.66,
                    "dewPoint": 23.16,
                    "humidity": 0.69,
                    "pressure": 1012.82,
                    "windSpeed": 2.87,
                    "windGust": 4.03,
                    "windBearing": 172,
                    "cloudCover": 0.86,
                    "uvIndex": 6,
                    "ozone": 244.59
                }
            ]
        },
        "offset": -3
    }
}

function getGeolocation() {
    return {
        "results": [
            {
                "address_components": [
                    {
                        "long_name": "11453-140",
                        "short_name": "11453-140",
                        "types": [
                            "postal_code"
                        ]
                    },
                    {
                        "long_name": "Jardim Progresso",
                        "short_name": "Jardim Progresso",
                        "types": [
                            "political",
                            "sublocality",
                            "sublocality_level_1"
                        ]
                    },
                    {
                        "long_name": "Guarujá",
                        "short_name": "Guarujá",
                        "types": [
                            "administrative_area_level_2",
                            "political"
                        ]
                    },
                    {
                        "long_name": "São Paulo",
                        "short_name": "SP",
                        "types": [
                            "administrative_area_level_1",
                            "political"
                        ]
                    },
                    {
                        "long_name": "Brazil",
                        "short_name": "BR",
                        "types": [
                            "country",
                            "political"
                        ]
                    }
                ],
                "formatted_address": "Jardim Progresso, Guarujá - SP, 11453-140, Brazil",
                "geometry": {
                    "bounds": {
                        "northeast": {
                            "lat": -23.937339,
                            "lng": -46.2857516
                        },
                        "southwest": {
                            "lat": -23.9393752,
                            "lng": -46.2881471
                        }
                    },
                    "location": {
                        "lat": -23.9380377,
                        "lng": -46.286281
                    },
                    "location_type": "APPROXIMATE",
                    "viewport": {
                        "northeast": {
                            "lat": -23.9370081197085,
                            "lng": -46.2856003697085
                        },
                        "southwest": {
                            "lat": -23.9397060802915,
                            "lng": -46.2882983302915
                        }
                    }
                },
                "place_id": "ChIJnbEASeADzpQRVlSmYnX3FiU",
                "types": [
                    "postal_code"
                ]
            }
        ],
        "status": "OK"
    }
}

module.exports = {
    getForecastCurrentGreat,
    getForecastCurrentSmall,
    getGeolocation
}